# Generated by Django 5.2.6 on 2025-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.AddField(
            model_name="patient",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
