# Generated by Django 5.2.6 on 2025-09-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_patient_age_remove_patient_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
    ]
