# Generated by Django 5.2.6 on 2025-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patient_address_patient_created_at_patient_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("billing", "Sent to Billing"),
                    ("consultation", "Doctor Consultation"),
                    ("lab", "Lab Requested"),
                    ("done", "Completed"),
                ],
                default="billing",
                help_text="Current workflow status for the patient",
                max_length=20,
            ),
        ),
    ]
