# Generated by Django 5.2.6 on 2025-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=50, null=True)),
                ("new_status", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="created_at",
            new_name="registered_at",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="address",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
