# Generated by Django 5.2.6 on 2025-09-24 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_patientstatushistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="national_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True, default="Unknown", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered", "Registered"),
                    ("sent_to_billing", "Sent to Billing"),
                    ("ready_for_doctor", "Ready for Doctor"),
                    ("lab_requested", "Lab Requested"),
                    ("xray_requested", "X-ray Requested"),
                    ("prescribed", "Prescribed"),
                    ("dispensed", "Dispensed"),
                ],
                default="registered",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientstatushistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="patients.patient",
            ),
        ),
    ]
