# Generated by Django 5.2.6 on 2025-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_patient_created_by_patient_national_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("intersex", "Intersex"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("sent_to_billing", "Sent to Billing"),
                    ("ready_for_doctor", "Ready for Doctor"),
                    ("lab_requested", "Lab Requested"),
                    ("xray_requested", "X-ray Requested"),
                    ("prescribed", "Prescribed"),
                    ("dispensed", "Dispensed"),
                ],
                default="registered",
                editable=False,
                max_length=50,
            ),
        ),
    ]
