# Generated by Django 5.2.6 on 2025-09-24 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_alter_patient_gender_alter_patient_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "national_id", "phone"),
                name="unique_patient_record",
            ),
        ),
    ]
