# Generated by Django 5.2.6 on 2025-10-02 13:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_patient_unique_patient_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientstatushistory",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="patient",
            name="unique_patient_record",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="registered_at",
        ),
        migrations.RemoveField(
            model_name="patientstatushistory",
            name="note",
        ),
        migrations.RemoveField(
            model_name="patientstatushistory",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 10, 2, 13, 43, 52, 682027, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_visit",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated unique patient number (e.g. PAT-0000123).",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number e.g. +254712345678",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientstatushistory",
            name="changed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 10, 2, 13, 44, 8, 159192, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who registered the patient (if known).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("intersex", "Intersex"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("triaged", "Triaged"),
                    ("waiting_for_doctor", "Waiting for Doctor"),
                    ("in_consultation", "In Consultation"),
                    ("ready_for_pharmacy", "Ready for Pharmacy"),
                    ("discharged", "Discharged"),
                ],
                default="registered",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="patientstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientstatushistory",
            name="new_status",
            field=models.CharField(default="registered", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patientstatushistory",
            name="old_status",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
