version: "3.9"

services:
  # -------------------------------
  # Django Backend Service
  # -------------------------------
  backend:
    build: ./backend                 # build image from backend/Dockerfile
    container_name: afya_backend
    volumes:
      - ./backend:/app               # mount local code so changes are live in container
    ports:
      - "8000:8000"                  # expose Django dev server on host:8000
    env_file:
      - .env                         # load env vars from project root .env
    depends_on:
      - db                           # start db before backend (ordering, not health-check)

  # -------------------------------
  # React Frontend Service (Vite)
  # -------------------------------
  frontend:
    build: ./frontend                # build image from frontend/Dockerfile
    container_name: afya_frontend
    volumes:
      - ./frontend:/app              # mount frontend source for hot reload
      - /app/node_modules            # keep node_modules inside the container
    ports:
      - "3000:3000"                  # expose Vite dev server on host:3000
    environment:
      - VITE_API_URL=http://localhost:8000  # your React app will call the API here
    depends_on:
      - backend

  # -------------------------------
  # PostgreSQL Database Service
  # -------------------------------
  db:
    image: postgres:15               # official Postgres image (no custom Dockerfile)
    container_name: afya_db
    restart: always                  # restart on failures
    environment:
      - POSTGRES_USER=${POSTGRES_USER}        # read from .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"                  # IMPORTANT: exposes DB to host at localhost:5432
    volumes:
      - db_data:/var/lib/postgresql/data     # persistent DB storage

  # -------------------------------
  # Optional: pgAdmin (web GUI) service
  # If you want a web pgAdmin instead of using your local pgAdmin app.
  # -------------------------------
  pgadmin:
    image: dpage/pgadmin4:latest        # official pgAdmin image
    container_name: afya_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}     # read from .env
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"   # access pgAdmin on http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # persist pgAdmin config

# -------------------------------
# Named volumes (persist data between restarts)
# -------------------------------
volumes:
  db_data:
  pgadmin_data:
