# Generated by Django 5.2.6 on 2025-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory"),
                    ("imaging", "Imaging"),
                    ("pharmacy", "Pharmacy"),
                    ("minor_procedure", "Minor Procedure"),
                    ("surgery", "Surgery"),
                    ("admission", "Admission"),
                    ("maternity", "Maternity"),
                    ("physiotherapy", "Physiotherapy"),
                    ("specialist_consultation", "Specialist Consultation"),
                ],
                default="consultation",
                max_length=100,
                null=True,
            ),
        ),
    ]
