# Generated by Django 5.2.6 on 2025-09-24 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_billing_charged_at_billing_charged_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="charged_by_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="patient_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="billing",
            name="charged_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="billing",
            name="service",
            field=models.CharField(
                blank=True,
                default="Registration / Consultation Fee",
                max_length=100,
                null=True,
            ),
        ),
    ]
