# Generated by Django 5.2.6 on 2025-10-06 07:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_billing_charged_at_alter_billing_service"),
        ("lab", "0002_alter_labrequest_options_alter_labresult_options_and_more"),
        ("patients", "0010_alter_patientstatushistory_options_and_more"),
        ("pharmacy", "0002_alter_dispenseline_quantity_dispensed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billing",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Billing",
                "verbose_name_plural": "Billings",
            },
        ),
        migrations.AddField(
            model_name="billing",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Record creation timestamp"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="currency",
            field=models.CharField(
                default="KES", help_text="Currency code", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="dispense",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to pharmacy dispense that generated this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="pharmacy.dispense",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly invoice id",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="lab_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to lab request that generated this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="lab.labrequest",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="report_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional external report/receipt ref",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Payment status",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last updated timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount charged for this billing record (Decimal, currency-aware).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="is_paid",
            field=models.BooleanField(
                default=False, help_text="Legacy boolean; derived from status"
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Patient this billing belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory"),
                    ("imaging", "Imaging"),
                    ("pharmacy", "Pharmacy"),
                    ("minor_procedure", "Minor Procedure"),
                    ("surgery", "Surgery"),
                    ("admission", "Admission"),
                    ("maternity", "Maternity"),
                    ("physiotherapy", "Physiotherapy"),
                    ("specialist_consultation", "Specialist Consultation"),
                ],
                default="consultation",
                help_text="Type of service billed (used for default pricing and reporting)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="billing",
            index=models.Index(
                fields=["invoice_number"], name="billing_bil_invoice_a75599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billing",
            index=models.Index(
                fields=["patient"], name="billing_bil_patient_ab6489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billing",
            index=models.Index(fields=["status"], name="billing_bil_status_495bdc_idx"),
        ),
    ]
