# Generated by Django 5.2.6 on 2025-10-06 09:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_billing_options_billing_created_at_and_more"),
        ("lab", "0002_alter_labrequest_options_alter_labresult_options_and_more"),
        ("pharmacy", "0002_alter_dispenseline_quantity_dispensed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount charged for this billing record (currency-aware).",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="currency",
            field=models.CharField(
                default="KES", help_text="Currency code (e.g. KES)", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="dispense",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a pharmacy dispense that generated this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="pharmacy.dispense",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="INV-AA-YYYYMMDD-XXXXXX",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="lab_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a lab request that generated this bill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="lab.labrequest",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="report_reference",
            field=models.CharField(
                blank=True,
                help_text="External reference like a printed receipt id",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory"),
                    ("imaging", "Imaging"),
                    ("pharmacy", "Pharmacy"),
                    ("minor_procedure", "Minor Procedure"),
                    ("surgery", "Surgery"),
                    ("admission", "Admission"),
                    ("maternity", "Maternity"),
                    ("physiotherapy", "Physiotherapy"),
                    ("specialist_consultation", "Specialist Consultation"),
                ],
                default="consultation",
                help_text="Service type (used for pricing and reporting).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Payment status",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method (e.g., cash, mpesa, card)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Optional payment reference (gateway/receipt id)",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.ForeignKey(
                        help_text="Billing this payment applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.billing",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
