# Generated by Django 5.2.6 on 2025-10-06 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_alter_billing_amount_alter_billing_created_at_and_more"),
        ("lab", "0002_alter_labrequest_options_alter_labresult_options_and_more"),
        ("pharmacy", "0002_alter_dispenseline_quantity_dispensed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("mpesa", "M-Pesa"),
                    ("insurance", "Insurance"),
                    ("card", "Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("other", "Other"),
                ],
                default="cash",
                help_text="Payment method",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Gateway/receipt reference",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount for this billing record",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="charged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded the billing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Record creation time"
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="currency",
            field=models.CharField(
                default="KES", help_text="Currency code, e.g., KES", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="dispense",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to pharmacy dispense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="pharmacy.dispense",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Invoice id",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="lab_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to lab request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="lab.labrequest",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="report_reference",
            field=models.CharField(
                blank=True, help_text="External ref or notes", max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory"),
                    ("imaging", "Imaging"),
                    ("pharmacy", "Pharmacy"),
                    ("minor_procedure", "Minor Procedure"),
                    ("surgery", "Surgery"),
                    ("admission", "Admission"),
                    ("maternity", "Maternity"),
                    ("physiotherapy", "Physiotherapy"),
                    ("specialist_consultation", "Specialist Consultation"),
                ],
                default="consultation",
                help_text="Type of service billed",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Record last updated time"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who recorded this payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
