# Generated by Django 5.2.6 on 2025-09-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultation", "0001_initial"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="drug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="pharmacy.drug"
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="consultation.prescription",
            ),
        ),
    ]
