# Generated by Django 5.2.6 on 2025-09-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0002_initial"),
        ("patients", "0009_patient_unique_patient_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="consultation",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="patients.patient",
            ),
        ),
    ]
