# Generated by Django 5.2.6 on 2025-09-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0003_remove_consultation_patient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consultation",
            name="patient_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
