# Generated by Django 5.2.6 on 2025-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0004_consultation_doctor_name_consultation_patient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose",
            field=models.PositiveIntegerField(
                blank=True, help_text="Amount per administration (numeric)", null=True
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of days (numeric)", null=True
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("od", "Once daily"),
                    ("bd", "Twice daily"),
                    ("tds", "Three times daily"),
                    ("qid", "Four times daily"),
                    ("q4h", "Every 4 hours"),
                    ("q6h", "Every 6 hours"),
                    ("stat", "Immediately (STAT)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oral", "Oral"),
                    ("iv", "Intravenous"),
                    ("im", "Intramuscular"),
                    ("sc", "Subcutaneous"),
                    ("topical", "Topical"),
                    ("inhalation", "Inhalation"),
                    ("sublingual", "Sublingual"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mg", "Milligram"),
                    ("g", "Gram"),
                    ("ml", "Milliliter"),
                    ("tablet", "Tablet"),
                    ("capsule", "Capsule"),
                    ("drop", "Drop"),
                    ("puff", "Puff"),
                ],
                max_length=50,
            ),
        ),
    ]
