# Generated by Django 5.2.6 on 2025-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultation",
            "0005_prescriptionitem_dose_prescriptionitem_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionitem",
            name="dose",
            field=models.PositiveIntegerField(
                blank=True, help_text="Amount per administration", null=True
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of days", null=True
            ),
        ),
    ]
