# Generated by Django 5.2.6 on 2025-10-02 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("doctor", "Medical Doctor / Physician"),
                    ("nurse", "Registered Nurse"),
                    ("pharmacist", "Pharmacist"),
                    ("lab", "Clinical Lab Scientist"),
                    ("reception", "Receptionist"),
                    ("admin", "Hospital Administrator"),
                ],
                help_text="Human-readable role. Use Groups for permissions.",
                max_length=50,
                null=True,
            ),
        ),
    ]
