# Generated by Django 5.2.6 on 2025-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at_user_department_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cardiology", "Cardiology"),
                    ("pediatrics", "Pediatrics"),
                    ("pharmacy", "Pharmacy"),
                    ("lab", "Laboratory"),
                    ("general", "General Medicine"),
                    ("admin", "Administration"),
                ],
                help_text="Select the department this staff belongs to.",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("doctor", "Medical Doctor / Physician"),
                    ("nurse", "Registered Nurse"),
                    ("pharmacist", "Pharmacist"),
                    ("lab", "Clinical Lab Scientist"),
                    ("reception", "Receptionist"),
                    ("admin", "Hospital Administrator"),
                ],
                help_text="Select a designation (Doctor, Nurse, Pharmacist, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Enter phone number e.g. +254712345678",
                max_length=10,
                null=True,
            ),
        ),
    ]
