# Generated by Django 5.2.6 on 2025-09-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "consultation",
            "0005_prescriptionitem_dose_prescriptionitem_duration_and_more",
        ),
        ("patients", "0009_patient_unique_patient_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_requests",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_requests",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="lab.labrequest",
                    ),
                ),
            ],
        ),
    ]
