# Generated by Django 5.2.6 on 2025-09-30 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultation",
            "0005_prescriptionitem_dose_prescriptionitem_duration_and_more",
        ),
        ("lab", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labrequest",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "Lab Request",
                "verbose_name_plural": "Lab Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="labresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lab Result",
                "verbose_name_plural": "Lab Results",
            },
        ),
        migrations.RemoveField(
            model_name="labrequest",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="result_details",
        ),
        migrations.AddField(
            model_name="labrequest",
            name="investigation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_requests",
                to="consultation.investigation",
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("sample_collected", "Sample Collected"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="requested",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="lab_results/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="result_json",
            field=models.JSONField(
                blank=True, help_text="Optional structured results (JSON).", null=True
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="result_text",
            field=models.TextField(
                default="", help_text="Structured or free-text result summary."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="labresult",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Set true once a senior tech/doctor verifies the result.",
            ),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_requests",
                to="consultation.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="test_name",
            field=models.CharField(
                help_text="Human friendly test name; used if investigation is not linked.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="labresult",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
