# Generated by Django 5.2.6 on 2025-09-29 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0009_patient_unique_patient_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("pulse", models.IntegerField(blank=True, null=True)),
                ("respiratory_rate", models.IntegerField(blank=True, null=True)),
                ("systolic_bp", models.IntegerField(blank=True, null=True)),
                ("diastolic_bp", models.IntegerField(blank=True, null=True)),
                ("oxygen_saturation", models.IntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("symptoms", models.TextField(blank=True, default="")),
                ("allergies", models.TextField(blank=True, default="")),
                ("current_medications", models.TextField(blank=True, default="")),
                ("is_urgent", models.BooleanField(default=False)),
                ("abnormal_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage record",
                "verbose_name_plural": "Triage records",
                "ordering": ["-created_at"],
            },
        ),
    ]
