# Generated by Django 5.2.6 on 2025-09-29 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_patient_unique_patient_record"),
        ("triage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triagerecord",
            options={},
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="abnormal_summary",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="current_medications",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="height",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="is_urgent",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="oxygen_saturation",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="pulse",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="respiratory_rate",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="triagerecord",
            name="weight",
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="attended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attended_triages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="heart_rate_bpm",
            field=models.PositiveIntegerField(
                default=0, help_text="Heart rate in beats per minute"
            ),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="height_cm",
            field=models.FloatField(default=0.0, help_text="Height in cm"),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="respiratory_rate_bpm",
            field=models.PositiveIntegerField(
                default=0, help_text="Respiratory rate in bpm"
            ),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="spo2_percent",
            field=models.FloatField(default=0.0, help_text="Oxygen saturation in %"),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="temperature_c",
            field=models.FloatField(default=0.0, help_text="Temperature in °C"),
        ),
        migrations.AddField(
            model_name="triagerecord",
            name="weight_kg",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
        migrations.AlterField(
            model_name="triagerecord",
            name="bmi",
            field=models.FloatField(blank=True, help_text="BMI kg/m²", null=True),
        ),
        migrations.AlterField(
            model_name="triagerecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="triagerecord",
            name="diastolic_bp",
            field=models.IntegerField(default=0, help_text="Diastolic BP in mmHg"),
        ),
        migrations.AlterField(
            model_name="triagerecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triage_records",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="triagerecord",
            name="systolic_bp",
            field=models.IntegerField(default=0, help_text="Systolic BP in mmHg"),
        ),
    ]
